Adding India to region (r1)
kairoaraujo/python-kodaksmarthome pull request #20
Opened 2021-07-07 17:17 UTC by raghavrithvik

India seems to have another region code. Haven't fully tested this.

2021-07-09 04:02 UTC, kairoaraujo requested changes
Fix the conflicts with master 
Also we need some tests those urls work 🤔

2021-07-09 04:02 UTC, kairoaraujo commented on kodaksmarthome/constants.py
> -        "URL_LOGOUT": "https://app-.kodaksmarthome.com/web/#/user/logout",
Fix the conflicts with master

2021-07-09 04:27 UTC, raghavrithvik commented
Installing HA on Python-env today. Will test before updating more. Thanks

2021-07-09 08:15 UTC, raghavrithvik commented
Giving up. I have no clue what to do to test out the URLs. Tried a venv install with local python package and got the same 'incorrect user/pw error".

2021-07-09 17:08 UTC, raghavrithvik commented
Changes made and tested. However camera stream not working. Entity appears though.

2021-07-09 17:08 UTC, raghavrithvik commented
reopened pull

2021-07-19 02:41 UTC, raghavrithvik commented
You may approve this PR. India region seems to login correctly. Might have to find a different proxy link for the camera stream. Any luck with that?

2021-07-22 12:21 UTC, merged