Update constants.py
kairoaraujo/python-kodaksmarthome pull request #5
Opened 2020-10-02 13:48 UTC by trev142

Added support for the HK region which seems to be used by us here in Australia

2020-10-06 12:43 UTC, kairoaraujo reviewed
Hi @trev142, is it working properly for this region?
Because I was having issues on UE region.

2020-10-07 13:41 UTC, kairoaraujo requested changes

2020-10-07 13:41 UTC, kairoaraujo commented on kodaksmarthome/__version__.py
> -__version__ = "0.1.1"
@trev142 , Just put as 0.2.0 as this is not a bug fix and some enhancement.

2020-10-09 09:58 UTC, kairoaraujo approved these changes

2020-10-09 10:01 UTC, kairoaraujo requested changes

2020-10-09 10:01 UTC, kairoaraujo commented on kodaksmarthome/constants.py
> +        },
The tests for PEP8 failed, please fix the following requirements:

```
pep8 run-test: commands[0] | flake8 --ignore=F401,W503
72
./kodaksmarthome/constants.py:21:9: E123 closing bracket does not match indentation of opening bracket's line
73
./kodaksmarthome/constants.py:22:1: W191 indentation contains tabs
74
./kodaksmarthome/constants.py:22:1: E101 indentation contains mixed spaces and tabs
75
./kodaksmarthome/constants.py:22:2: E131 continuation line unaligned for hanging indent
76
./kodaksmarthome/constants.py:23:1: E101 indentation contains mixed spaces and tabs
77
./kodaksmarthome/constants.py:28:9: E123 closing bracket does not match indentation of opening bracket's line
78
```

2021-07-05 16:49 UTC, raghavrithvik commented
How do I get this updated to work with the HA component?

2021-07-07 12:35 UTC, kairoaraujo commented
Closed due to PR #13

2021-07-07 12:35 UTC, closed without merging